# Generated by Django 6.1.1 on 2026-09-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('rider_type', models.CharField(choices=[('Salary-based', 'Salary-based'), ('Per-order', 'Per-order')], max_length=20)),
                ('assigned_store', models.CharField(max_length=100)),
                ('assigned_zone', models.CharField(max_length=100)),
                ('payout_method', models.CharField(choices=[('UPI', 'UPI'), ('Bank Account', 'Bank Account')], max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driving_license_number', models.CharField(max_length=50)),
                ('driving_license_document', models.URLField()),
                ('aadhaar_number', models.CharField(max_length=20)),
                ('aadhaar_document', models.URLField()),
                ('vehicle_rc_number', models.CharField(max_length=50)),
                ('vehicle_rc_document', models.URLField()),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
                ('activate_immediately', models.BooleanField()),
                ('online_status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('On Break', 'On Break'), ('On Delivery', 'On Delivery')], default='Offline', max_length=20)),
                ('current_order', models.CharField(blank=True, max_length=100, null=True)),
                ('cash_in_hand', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_undeposited_cash', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
