# Generated by Django 4.2.30 on 2026-09-07 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField()),
                ('rider_type', models.CharField(choices=[('Salary-based', 'Salary-based'), ('Per-order', 'Per-order')], max_length=20)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_order_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_km_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('assigned_store', models.CharField(max_length=100)),
                ('assigned_zone', models.CharField(max_length=100)),
                ('payout_method', models.CharField(choices=[('UPI', 'UPI'), ('Bank Account', 'Bank Account')], max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driving_license_number', models.CharField(max_length=50)),
                ('driving_license_document', models.FileField(upload_to='riders/driving_license/')),
                ('driving_license_verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], default='Pending', max_length=10)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('aadhaar_document', models.FileField(upload_to='riders/aadhaar/')),
                ('aadhaar_verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], default='Pending', max_length=10)),
                ('vehicle_rc_number', models.CharField(max_length=50)),
                ('vehicle_rc_document', models.FileField(upload_to='riders/vehicle_rc/')),
                ('vehicle_rc_verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], default='Pending', max_length=10)),
                ('account_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked'), ('Pending', 'Pending'), ('Suspend', 'Suspend'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('activate_immediately', models.BooleanField(default=False)),
                ('online_status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('On Break', 'On Break'), ('On Delivery', 'On Delivery')], default='Offline', max_length=20)),
                ('current_order', models.CharField(blank=True, max_length=100, null=True)),
                ('cash_in_hand', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_undeposited_cash', models.BooleanField(default=False)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiderPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash')], max_length=20)),
                ('payout_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='rider.rider')),
            ],
        ),
        migrations.CreateModel(
            name='RiderDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='rider.rider')),
            ],
        ),
    ]
