# Generated by Django 4.2.30 on 2026-09-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
