# Generated by Django 4.2.30 on 2026-09-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_riderdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='aadhaar_document',
            field=models.FileField(blank=True, null=True, upload_to='riders/aadhaar/'),
        ),
        migrations.AddField(
            model_name='rider',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='account_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='rider',
            name='activate_immediately',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rider',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='assigned_store',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='assigned_zone',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='base_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='cash_in_hand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rider',
            name='current_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='driving_license_document',
            field=models.FileField(blank=True, null=True, upload_to='riders/driving_license/'),
        ),
        migrations.AddField(
            model_name='rider',
            name='driving_license_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='has_undeposited_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rider',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='online_status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('On Break', 'On Break'), ('On Delivery', 'On Delivery')], default='Offline', max_length=20),
        ),
        migrations.AddField(
            model_name='rider',
            name='payout_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Bank Account', 'Bank Account')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='per_km_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='per_order_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='rider_type',
            field=models.CharField(choices=[('Salary-based', 'Salary-based'), ('Per-order', 'Per-order')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='vehicle_rc_document',
            field=models.FileField(blank=True, null=True, upload_to='riders/vehicle_rc/'),
        ),
        migrations.AddField(
            model_name='rider',
            name='vehicle_rc_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='RiderPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash')], max_length=20)),
                ('payout_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='rider.rider')),
            ],
        ),
    ]
