# Generated by Django 4.2.30 on 2026-09-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0004_rider_aadhaar_document_rider_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='aadhaar_document',
            field=models.FileField(default='', upload_to='riders/aadhaar/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rider',
            name='aadhaar_number',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rider',
            name='driving_license_document',
            field=models.FileField(default='', upload_to='riders/driving_license/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rider',
            name='vehicle_rc_document',
            field=models.FileField(default='', upload_to='riders/vehicle_rc/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RiderDeposit',
        ),
    ]
