# Generated by Django 4.2.30 on 2026-09-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0006_riderdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='aadhaar_verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='rider',
            name='driving_license_verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='rider',
            name='vehicle_rc_verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='rider',
            name='account_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked'), ('Pending', 'Pending'), ('Suspend', 'Suspend'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
