# Generated by Django 4.2.30 on 2026-09-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0007_rider_aadhaar_verification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='account_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked'), ('Pending', 'Pending'), ('Suspend', 'Suspend'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
