# Generated by Django 6.1.1 on 2026-09-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('rider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_range', models.CharField(max_length=50)),
                ('base_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rider_type', models.CharField(choices=[('Salary', 'Salary'), ('Per-order', 'Per-order')], max_length=20)),
                ('zone', models.CharField(max_length=100)),
                ('vehicle', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
