# Generated by Django 4.2.30 on 2026-09-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0008_riderrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='aadhaar_verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Mark as Verified', 'Mark as Verified'), ('Expired', 'Expired'), ('Invalid Document', 'Invalid Document'), ('Document not clear', 'Document not clear'), ('Details Mismatch', 'Details Mismatch')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='rider',
            name='driving_license_verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Mark as Verified', 'Mark as Verified'), ('Expired', 'Expired'), ('Invalid Document', 'Invalid Document'), ('Document not clear', 'Document not clear'), ('Details Mismatch', 'Details Mismatch')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='rider',
            name='vehicle_rc_verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Mark as Verified', 'Mark as Verified'), ('Expired', 'Expired'), ('Invalid Document', 'Invalid Document'), ('Document not clear', 'Document not clear'), ('Details Mismatch', 'Details Mismatch')], default='Pending', max_length=30),
        ),
    ]
