# Generated by Django 6.1.1 on 2026-09-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0008_riderrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderrate',
            name='distance_from',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderrate',
            name='distance_to',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderrate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riderrate',
            name='rate_type',
            field=models.CharField(default='per order', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderrate',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
