# Generated by Django 4.2.30 on 2026-09-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0009_alter_rider_aadhaar_verification_status_and_more'),
        ('rider', '0009_riderrate_distance_from_riderrate_distance_to_and_more'),
    ]

    operations = [
    ]
