# Generated by Django 4.2.30 on 2026-09-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0011_remove_riderrate_distance_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderrate',
            name='distance_range',
        ),
        migrations.AddField(
            model_name='riderrate',
            name='distance_from',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='riderrate',
            name='distance_to',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
