# Generated by Django 6.1.1 on 2026-09-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0012_remove_riderrate_distance_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='completion_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='total_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='total_orders_delivered',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
