# Generated by Django 6.1.1 on 2026-09-09 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0013_rider_average_rating_rider_completion_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('present', models.PositiveIntegerField(default=0)),
                ('absent', models.PositiveIntegerField(default=0)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='rider.rider')),
            ],
        ),
        migrations.CreateModel(
            name='RiderLoginLogoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logout_logs', to='rider.rider')),
            ],
        ),
    ]
