# Generated by Django 6.1.1 on 2026-09-09 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0014_riderattendance_riderloginlogoutlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderCurrentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('pickup', models.CharField(blank=True, max_length=200, null=True)),
                ('drop', models.CharField(blank=True, max_length=200, null=True)),
                ('customer', models.CharField(blank=True, max_length=200, null=True)),
                ('order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_assignment', to='rider.rider')),
            ],
        ),
    ]
