# Generated by Django 6.1.1 on 2026-09-09 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0015_ridercurrentassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], max_length=20)),
                ('order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='rider.rider')),
            ],
        ),
    ]
