# Generated by Django 6.1.1 on 2026-09-09 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0016_riderorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderSalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Paid', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='rider.rider')),
            ],
        ),
    ]
