# Generated by Django 6.1.1 on 2026-09-09 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0017_ridersalaryhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100)),
                ('requirement', models.CharField(max_length=200)),
                ('progress', models.CharField(blank=True, max_length=50, null=True)),
                ('remaining', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=255)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=30)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='rider.rider')),
            ],
        ),
    ]
