# Generated by Django 6.1.1 on 2026-09-09 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0018_riderincentive'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='rider.rider')),
            ],
        ),
    ]
