# Generated by Django 6.1.1 on 2026-09-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0019_rideractivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderrate',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
