# Generated by Django 4.2.30 on 2026-09-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ('rider', '0001_initial'),

    ]

    operations = [
        migrations.CreateModel(
            name='RiderRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rider_type', models.CharField(max_length=20)),
                ('zone', models.CharField(max_length=100)),
                ('vehicle', models.CharField(max_length=100)),
                ('rate_type', models.CharField(choices=[('Per KM', 'Per KM'), ('Fixed', 'Fixed')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
